server:
  port: 8081
  error:
    include-stacktrace: on-trace-param

spring:
  h2:
  console:
  enabled: true
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/devdb;
    username: sa
    password:
